server:
  port: 8888
  
spring:
  application:
    name: ms-admin-config-server  
          
#Configuracion local

#  profiles:
#    active: native
#
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: file:///D:/COSASDELUIS/CursosGalaxy/Micro-Java/ms-gestion-config-data

#Configuracion cloud
  cloud:
    config:
      server:
        git:
          uri: https://github.com/loufresh23/curso-micro-java.git
          searchPaths: ms-gestion-config-data 
          username: ${USER_NAME}
          password: ${USER_PASSWORD}
          default-label: 1.Config-server
          clone-on-start: true
